Up version bounds, with for support ghc 9.8
google/proto-lens pull request #466
Opened 2024-04-06 12:31 UTC by edsko

`proto-lens` and `proto-lens-runtime` are compatible with

* `base` 4.19 (ghc 9.8.2 comes with 4.19.1.0)
* `bytestring` 0.12 (ghc 9.8.2 comes with 0.12.1.0)
* `containers` 0.7
* `deepseq` 1.5 (ghc 9.8.2 comes with 1.5.0.0)
* `ghc-prim` 0.11 (ghc 9.8.2 comes with 0.11.0)
* `primitive` 0.9

Closes #459.
Closes #461.

2024-04-06 12:33 UTC, edsko commented
This depends on https://github.com/google/ghc-source-gen/pull/113 being released to Hackage. It builds when adding a `source-repository-package` to `cabal.project` with

```
source-repository-package
  type: git
  location: https://github.com/google/ghc-source-gen
  tag: d9707003aa9e922afc08c4f2b19d550c8dd344d3
```

2024-04-06 12:45 UTC, edsko commented
Did the CLA thing, but this will still fail (I think) because it still depends on the `ghc-sourc-gen` release.

2024-04-07 18:51 UTC, blackgnezdo commented
Could you also grab the package.yaml changes from https://github.com/blackgnezdo/proto-lens/tree/ghc98?

2024-04-07 18:54 UTC, blackgnezdo requested changes
Please pull in blackgnezdo:ghc98

2024-04-08 03:01 UTC, blackgnezdo commented
Let's merge #467 instead as it covers everything we need for the release. Thanks for sending the original change and giving me impulse to finish this.

2024-09-26 17:27 UTC, closed without merging